# Dependencies

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "GD's Blog"
tagline:          ''
description:      'a GD Blog'
url:              https://www.gregorymdunaway.com
baseurl:          ''

author:
  name:           'Gregory Dunaway'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
version:          0.1

github:
  repo:           https://github.com/scrawnylizard/blog

plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages
  - jekyll-gist

disqus:
  shortname: scrawnylizard
