# Dependencies

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "Itsablog"
tagline:          ''
description:      ''
url:              https://www.gregorymdunaway.com
baseurl:          ''

author:
  name:           'Gregory Dunaway'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/scrawnylizard/blog

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: scrawnylizard
